---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-prod-wrk-deployment
  labels:
    app: app-prod-wrk
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-prod-wrk
  template:
    metadata:
      labels:
        app: app-prod-wrk
        env: prod
    spec:
      containers:
        - name: app-prod-wrk
          image: rhodgesd/coe332-final-wrk:0.1.0
          imagePullPolicy: Always
          env:
          - name: REDIS_IP
            value: app-prod-redis-service