---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: app-prod-redis
    labels:
        env: prod
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: nfs
    resources:
        requests:
            storage: 1Gi
