---
version: '3'
services:
    wallen-db:
        image: redis:6.2.3
        container_name: ehc586-db
        ports:
            - 6407:6379
        user: "827385:815499"
        volumes:
            - ./data/:/data/
    wallen-api:
        build:
            context: ../
            dockerfile: ${PWD}/docker/Dockerfile.api
        container_name: ehc586-api
        environment:
            - REDIS_IP=ehc586-db
        ports:
            - 5007:5000
        depends_on:
            - ehc586-db
    wallen-wrk:
        build:
            context: ../ 
            dockerfile: ${PWD}/docker/Dockerfile.wrk
        container_name: ehc586-wrk
        environment:
            - REDIS_IP=ehc586-db
        depends_on:
            - ehc586-db
