FROM python:3.9

RUN pip3 install Flask==2.0.3 \
                 redis==4.2.1 \
                 hotqueue==0.2.8 \
                 pytest==7.0.1

COPY ./src/api.py /app/
COPY ./src/weather_data.json /app/weather_data.json

WORKDIR /app/
ENTRYPOINT ["python3"]
CMD ["api.py"]
